2024-10-21 12:15:19,075 INFO    MainThread:1485282 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-10-21 12:15:19,075 INFO    MainThread:1485282 [wandb_setup.py:_flush():76] Configure stats pid to 1485282
2024-10-21 12:15:19,076 INFO    MainThread:1485282 [wandb_setup.py:_flush():76] Loading settings from /home/msinnona/.config/wandb/settings
2024-10-21 12:15:19,076 INFO    MainThread:1485282 [wandb_setup.py:_flush():76] Loading settings from /mnt/disk2/msinnona/visdecode/eurographics/wandb/settings
2024-10-21 12:15:19,076 INFO    MainThread:1485282 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-10-21 12:15:19,076 INFO    MainThread:1485282 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-10-21 12:15:19,077 INFO    MainThread:1485282 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-10-21 12:15:19,077 INFO    MainThread:1485282 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-10-21 12:15:19,077 INFO    MainThread:1485282 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/disk2/msinnona/visdecode/eurographics/wandb/run-20241021_121519-y7n3i3ur/logs/debug.log
2024-10-21 12:15:19,077 INFO    MainThread:1485282 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/disk2/msinnona/visdecode/eurographics/wandb/run-20241021_121519-y7n3i3ur/logs/debug-internal.log
2024-10-21 12:15:19,077 INFO    MainThread:1485282 [wandb_init.py:init():566] calling init triggers
2024-10-21 12:15:19,077 INFO    MainThread:1485282 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-10-21 12:15:19,077 INFO    MainThread:1485282 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 6n2tw26f
2024-10-21 12:15:19,079 INFO    MainThread:1485282 [wandb_run.py:_finish():1970] finishing run martinsinnona/visdecode/6n2tw26f
2024-10-21 12:15:19,080 INFO    MainThread:1485282 [jupyter.py:save_history():445] not saving jupyter history
2024-10-21 12:15:19,080 INFO    MainThread:1485282 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-10-21 12:15:19,080 INFO    MainThread:1485282 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-10-21 12:15:19,080 INFO    MainThread:1485282 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-10-21 12:15:19,081 INFO    MainThread:1485282 [wandb_run.py:_restore():2193] restore
2024-10-21 12:15:19,081 INFO    MainThread:1485282 [wandb_run.py:_restore():2199] restore done
2024-10-21 12:16:08,973 INFO    MainThread:1485282 [wandb_init.py:init():616] starting backend
2024-10-21 12:16:08,973 INFO    MainThread:1485282 [wandb_init.py:init():620] setting up manager
2024-10-21 12:16:08,985 INFO    MainThread:1485282 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-21 12:16:08,986 INFO    MainThread:1485282 [wandb_init.py:init():628] backend started and connected
2024-10-21 12:16:09,003 INFO    MainThread:1485282 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-10-21 12:16:09,003 INFO    MainThread:1485282 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-10-21 12:16:09,003 INFO    MainThread:1485282 [wandb_init.py:init():720] updated telemetry
2024-10-21 12:16:09,061 INFO    MainThread:1485282 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
